export const initialRightHeaderLayout = [
    {
        key: 1,
        name: 'webex',
        iconName: 'webex_16',
        label: 'Webex',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        key: 2,
        name: 'outdial',
        iconName: 'audio-call_16',
        label: 'Outdial',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        key: 3,
        name: 'notifications',
        iconName: 'alert_16',
        label: 'Notifications',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        key: 4,
        name: 'stateSelector',
        variant: 'available',
        label: 'Available',
        isDraggable: true,
        canDelete: false,
    },
    {
        key: 5,
        name: 'profile',
        title: 'Widget Craft',
        label: 'Profile',
        isDraggable: false,
        canDelete: false,
    },
]