export const initialRightHeaderLayout = [
    {
        id: 1,
        type: 'circle-button',
        name: 'webex',
        iconName: 'webex_16',
        label: 'Webex',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        id: 2,
        type: 'circle-button',
        name: 'outdial',
        iconName: 'audio-call_16',
        label: 'Outdial',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        id: 3,
        type: 'circle-button',
        name: 'notifications',
        iconName: 'alert_16',
        label: 'Notifications',
        isDraggable: true,
        canDelete: true,
        iconSet: "preferMomentumDesign",
    },
    {
        id: 4,
        type: 'state-button',
        name: 'stateSelector',
        variant: 'available',
        label: 'Available',
        isDraggable: true,
        canDelete: false,
    },
    {
        id: 5,
        type: 'avatar',
        name: 'profile',
        title: 'Widget Craft',
        label: 'Profile',
        isDraggable: false,
        canDelete: false,
    },
]