export const iconList = [
    { value: "accessories-active", label: "Accessories Active" },
    { value: "adjust-audio", label: "Adjust Audio" },
    { value: "alert-muted", label: "Alert Muted" },
    { value: "announcement", label: "Announcement" },
    { value: "ask-for-help", label: "Ask For Help" },
    { value: "arrow-circle-right", label: "Arrow Circle Right" },
    { value: "arrow-tail-up", label: "Arrow Tail Up" },
    { value: "audio-video", label: "Audio Video" },
    { value: "back", label: "Back" },
    { value: "blocked", label: "Blocked" },
    { value: "camera", label: "Camera" },
    { value: "commenting", label: "Commenting" },
    { value: "dashboard", label: "Dashboard" },
    { value: "data-usage", label: "Data Usage" },
    { value: "delete", label: "Delete" },
    { value: "device-connection", label: "Device Connection" },
    { value: "directory", label: "Directory" },
    { value: "email-read", label: "Email Read" },
    { value: "endpoint-mx800-dual", label: "Endpoint Mx800 Dual" },
    { value: "error", label: "Error" },
    { value: "exit-room", label: "Exit Room" },
    { value: "feedback-active", label: "Feedback Active" },
    { value: "file-excel", label: "File Excel" },
    { value: "file-powerpoint", label: "File Powerpoint" }
];